### PR TITLE
[202209] moved assignment2 resource files to assignment2 folder

### PR DESCRIPTION
**Pull request by john-choi-pocu-ta**

### CODE REVIEW

**Comment by chrisyoon01** [comment]
@john-choi-pocu-ta The write up says these files are in Assignment2 folder, but it seems like these files are in src/blah/blah/blah folder. Move them to the root of Assignment2 folder

**Review by chrisyoon01 — CHANGES_REQUESTED** [review]
see comment

**Comment by john-choi-pocu-ta** [comment]
NOTE: Changes should be merged AFTER the end of 202205 term

**Review by chrisyoon01 — APPROVED** [review]

**Comment by john-choi-pocu-ta** [comment]
Keeping the output .log files in the Resources folder. Closing

**Pull request closed without merging**
